//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace AssemblyCSharp
{
	public class LightProjectile : Projectile
	{
		public Light[] lights;
		public AnimationCurve fadeCurve;
		public float fadeTime = 1;

		private float[] _lightIntensities;
		private float _startFade;
		public LightProjectile ()
		{
		}
		public override void Start()
		{
			base.Start ();
			_lightIntensities =  new float[lights.Length];

			FindObjectOfType<RoachController> ().LightLaunched (gameObject);

			for(int i=0; i<lights.Length; i++)
			{
				_lightIntensities[i] = lights[i].intensity;
			}
		}
		public override void Update(){
			base.Update ();
			if (Time.time > _startTime + (lifeTime - fadeTime)) 
			{
				float scale = fadeCurve.Evaluate ((Time.time - ((_startTime + lifeTime) - fadeTime)) / fadeTime);
				for (int i=0; i<lights.Length; i++) 
				{
					transform.localScale = new Vector3 (scale, scale, scale);
					lights [i].intensity = _lightIntensities [i] * scale;
				}
			}
		}
		void OnCollisionEnter(Collision col)
		{
			Destroy (gameObject);
		}
	}
}

